#!/bin/sh
case "${JOB_BASE_NAME}" in
       *v8a*)
               ln -sfvT /opt/OSELAS.Toolchain-2024.11.1/arm-v7a-linux-gnueabihf/gcc-14.2.1-clang-19.1.7-glibc-2.40-binutils-2.43.1-kernel-6.11.6-sanitized/bin selected_toolchain_r5
               ;;
esac