pg_uri: postgres://juicepress:juicepress@127.0.0.1:2345/juicepress
scoring: weighted_linear_combination
selection:
  - is_userspace_elf
cfactor:
  - binary_string
  - filename
  - taint_symbol
iofactor:
  - nsrl
  - alpine
  - ubuntu
  - open_wrt
  - open_embedded
  - ptx_dist
  - buildroot
  - manpage

